### ISSUE TITLE
seleniumwire.proxy.handler:code 400, message Bad request syntax

### ISSUE THREAD

**Issue by woswos** [wkeeling/selenium-wire#116]
Hi,
First of all, thank you so much for developing this library! I tried using Selenium Wire like [mitmproxy's upstream mode](https://docs.mitmproxy.org/stable/concepts-modes/#upstream-proxy) by running the following code. mitmproxy doesn't support socks proxy in the upstream proxy, but Selenium Wire does.
```
from seleniumwire import webdriver
import logging
logging.basicConfig(level=logging.DEBUG)

options = {
    'proxy': {
        'http': 'socks5://127.0.0.1:9050',   # This goes to Tor
        'https': 'socks5://127.0.0.1:9050',  # This goes to Tor
	'verify_ssl': False,
	'suppress_connection_errors': False
    }
}

driver = webdriver.Firefox(seleniumwire_options=options)
driver.get("URL")

while True:
	pass
```
So, my purpose was to keep the Selenium Wire's internal proxy running, as if it was running in the standalone mode and chain it with Tor. I know the standalone mode already exists but it is not possible to specify the upstream proxy in the standalone mode. _This might be my little feature request within this issue 😀_

Later, I gathered the port number for Selenium Wire's proxy from the terminal window and I plugged it into [Tor Browser's proxy configuration settings](https://tb-manual.torproject.org/running-tor-browser/). Tor Browser is a modified version of Firefox and it is compatible with Selenium.

During the start-up, the Tor Browser negotiates with various Tor relays to establish a circuit. The negotiations work great over Selenium Wire's proxy until a point, and I keep getting the "Bad request syntax" after that point:
```
DEBUG:seleniumwire.proxy.handler:78.31.64.201:443 200
DEBUG:seleniumwire.proxy.handler:51.77.251.192:443 200
DEBUG:seleniumwire.proxy.handler:95.216.33.58:443 200
DEBUG:seleniumwire.proxy.handler:78.46.104.112:443 200
DEBUG:seleniumwire.proxy.handler:188.24.66.96:443 200
DEBUG:seleniumwire.proxy.handler:code 400, message Bad request syntax ('\x00\x00\x07\x00\x06\x00\x03\x00\x04\x00\x05')
NoneType: None
DEBUG:seleniumwire.proxy.handler:95.216.33.58:443 HTTPStatus.BAD_REQUEST
DEBUG:seleniumwire.proxy.handler:code 400, message Bad request syntax ('\x00\x00\x07\x00\x06\x00\x03\x00\x04\x00\x05')
NoneType: None
DEBUG:seleniumwire.proxy.handler:code 400, message Bad request syntax ('\x00\x00\x07\x00\x06\x00\x03\x00\x04\x00\x05')
NoneType: None
```
Do you have any idea why this happens? What is this error even? What I am doing is probably out of the scope of Selenium Wire library but I still wanted to get your opinion.

**Comment by wkeeling** [comment]
Thanks for taking the trouble to raise such a detailed issue.

The "Bad request syntax" response you're getting back is curious, as are the `NoneType: None` lines that occur after. I don't know why that's happening although it could well be caused by something Selenium Wire is doing, or possibly something the underlying socks code is doing (Selenium Wire uses code from [PySocks](https://github.com/Anorov/PySocks) under the covers). Socks support is quite a new addition to the library.

I'll try and reproduce and debug some more. It would be good to fix Selenium Wire if a problem does exist in the socks handling. If you have any further insights too let me know.

I'll also raise a separate issue about better configuration for standalone mode (I recently wanted to run the proxy standalone with `verify_ssl = False` but realised I couldn't!). You can pass the proxy config via [environment variables](https://github.com/wkeeling/selenium-wire#proxies) too btw, but not any other options yet.

**Comment by woswos** [comment]
Thank you for your quick reply. In the meantime, I talked to Tor developers and I realized what I was doing was wrong. The example I gave was placing the Selenium Wire proxy after the Tor proxy, instead of placing right between the browser and the Tor proxy. So, please don't spend your time on reproducing this :) 

I placed a working example in [this GitHub gist](https://gist.github.com/woswos/38b921f0b82de009c12c6494db3f50c5). Feel free to include it in the documentation if it seems appropriate.

**Comment by wkeeling** [comment]
Many thanks for your working example. I'll look at including that in a separate area in the docs. Could be useful for others.
