### ISSUE TITLE
Check if all requests have completed/timed out?

### ISSUE THREAD

**Issue by ethanscorey** [wkeeling/selenium-wire#162]
First of all, thanks for creating this package -- it's truly a godsend! I'm trying to write something similar to this code from your documentation:

```python
# Click a button that triggers a background request to https://server/api/products/12345/
button_element.click()

# Wait for the request/response to complete
request = driver.wait_for_request('/api/products/12345/$')
```

The difference is that I want it to wait until _every_ request initiated by that click has completed (successfully or not) before returning a list of all the completed requests, without any pre-existing knowledge about what requests to expect. 

Is that possible to do with any pre-existing methods in the package? Or is this a new feature request? I came up with this hacky solution, but I feel like there has to be a better way, particularly since this will raise an exception if any of the requests time out:

```python
del driver.requests
button_element.click()
requests = [driver.wait_for_request(re.escape(req.url)) for url in driver.requests]
```

**Comment by wkeeling** [comment]
Thanks for raising this. As you discovered Selenium Wire unfortunately doesn't have anything built in to support waiting for every request triggered by an action. The problem is that Selenium Wire doesn't know how many requests it should expect and so wouldn't know when to stop waiting. 

One other problem with `[driver.wait_for_request(re.escape(req.url)) for url in driver.requests]` is that not all requests may have been made when the list comprehension is built from `driver.requests` (assuming `click()` is async) and the browser may still be transmitting.

There is another possible solution though:

```
del driver.requests
button_element.click()

idle = driver.execute_async_script("""
  window.requestIdleCallback(() => {
    arguments[0](true)
  })
""")
```

That will block until the browser's event loop is idle, which basically means all requests should have completed. Perhaps worth a try. We may even look at incorporating that into the API as we've had a similar question to this raised in the past.

**Comment by ethanscorey** [comment]
Thanks for this helpful (and speedy) reply! I guess now that I think about it more, there's no definitive way to confirm that _all_ requests have been completed, but this seems like a good solution for the vast majority of cases.
