### ISSUE TITLE
Executing the js with seleniumwire occur socket timeout issue when crawling facebook mobile version

### ISSUE THREAD

**Issue by seanng123456789** [wkeeling/selenium-wire#173]
Hi, I am sorry I may not know the rules in github as I am a newbie to github
The exception is occur when I execute the javascript
Then the fb page will stop loading like the error.PNG, the highlighted in red circle is stop loading so that I can't crawl the post information
I am using ten different user agent with different header and using nord vpn

[code.txt](https://github.com/wkeeling/selenium-wire/files/5578377/code.txt)
[exception.txt](https://github.com/wkeeling/selenium-wire/files/5578378/exception.txt)
![error](https://user-images.githubusercontent.com/74837842/99887659-0585f300-2c81-11eb-8b19-6698fc96d4df.PNG)

**Comment by seanng123456789** [comment]
Thank you so much

**Comment by wkeeling** [comment]
Thanks for raising this issue.

You mentioned that you are using nordvpn, but you don't have any proxy configured in the options you're passing to the webdriver. I don't have experience with nordvpn myself, but somebody else recently reported an issue when using nordvpn #163 . They had to specify the proxy in the [Selenium Wire options](https://github.com/wkeeling/selenium-wire#proxies), and ensure that they were using port 88. Perhaps that could be related?

**Comment by seanng123456789** [comment]
Let me try then, thank you.

**Comment by seanng123456789** [comment]
But the wired thing is that I was running for a while, just got this issue recently. Also, if I set the proxy, it seems facebook can detect and block me.

BTW:
	
[code2.txt](https://github.com/wkeeling/selenium-wire/files/5579957/code2.txt)


is this config right?

**Comment by wkeeling** [comment]
The config looks ok, except I notice you've specified a `http` proxy in the `https` section:
```
'https': 'http://83.97.23.90:18080',
```

You mention that it had been running OK for a while, and then you suddenly started getting this issue, so perhaps the issue is not related to the proxy settings.

It may also be worth trying the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends) to see whether that resolves the problem. To switch, first install mitmproxy with:

```
pip install mitmproxy
```
Once installed, set the backend option in Selenium Wire's options to mitmproxy:

```
seleniumwire_options = {
    'backend': 'mitmproxy'
}

#for setting headless into selenium options
options = webdriver.ChromeOptions()
options.headless = True

driver = webdriver.Chrome(
    options=options, 
    seleniumwire_options=seleniumwire_options, 
    executable_path=r"webDriver\window\chromedriver.exe"
)

driver.header_overrides = headers
driver.get(profile_url)
```

**Comment by seanng123456789** [comment]
O thank you so much, 
i am studying #163 and see how to set nordvpn to the proxy. 
One more question, if I use the VPN service for my internet connection, is it necessary to set proxy in selenium wire? Or I just no need to proxy in general?

**Comment by wkeeling** [comment]
If you are using an upstream proxy server for your vpn, then yes you'll need to specify this in Selenium Wire's options. This is because Selenium Wire overrides the browser's own proxy settings (or system settings if the browser is using those) to inject its own proxy for capturing requests. In order to tell that proxy about your upstream proxy, you have to use the `proxy` option.

**Comment by seanng123456789** [comment]
Thank you for your suggestion, let me take time to try the above method.
