### ISSUE TITLE
selenium-wire PR_CONNECT_ABORTED_ERROR

### ISSUE THREAD

**Issue by Quinlivanner** [wkeeling/selenium-wire#203]
When I use Pycharm to run the program, everything is fine, but when I use pyinstaller to package it into an exe to run, he will prompt: failed to establish a secure connection, PR_CONNECT_ABORTED_ERROR, and unable to open the web page, I want to know, is there any way to solve Is it

**Comment by IModThings** [comment]
I have the same issue using normal pip (in a venv). 
![image](https://user-images.githubusercontent.com/48841681/106109076-918b1f80-60f5-11eb-9ee3-9000b4838b22.png)

Weird thing is it worked before but then it suddenly stopped working.
I since tried upgrading pip and selenium-wire and deleting the Gecko driver (I use webdriver-manager).

I'm running Fedora 33. Python version 3.8. selenium-wire version 3.0.5.

Using plain selenium still works.

**Comment by Quinlivanner** [comment]
> I have the same issue using normal pip (in a venv).
> ![image](https://user-images.githubusercontent.com/48841681/106109076-918b1f80-60f5-11eb-9ee3-9000b4838b22.png)
> 
> Weird thing is it worked before but then it suddenly stopped working.
> I since tried upgrading pip and selenium-wire and deleting the Gecko driver (I use webdriver-manager).
> 
> I'm running Fedora 33. Python version 3.8. selenium-wire version 3.0.5.
> 
> Using plain selenium still works.

When I use selenium-wire, whether it is firefox or chrome, this problem is the same, but I tried another method yesterday is to add a hook file to the pyinstaller folder and write two lines of code, and then it started to work , But the network connection is very unstable

**Comment by wkeeling** [comment]
I created a .exe using PyInstaller, a simple test script and the latest version of Selenium Wire (4.2.0) and the .exe ran without any problems. I didn't have to carry out any extra steps (e.g. create a hook). This is likely because from version 4 onwards, Selenium Wire no longer has an external dependency on openssl.exe for certificate generation. Closing this one for now.
