### ISSUE TITLE
Issue running selenium wire on Safari browser 

### ISSUE THREAD

**Issue by sluthra-globallogic** [wkeeling/selenium-wire#23]
HI Team, 

I am a beginner with the selenium-wire, I wanted to override headers on safari, I did all the configuration as mentioned in the document but after setting proxy as localhost and random port, I am able to run scripts but getting no internet access. 

Need your assistance on this. 

Regards,
Sukrant

**Comment by wkeeling** [comment]
Hi @sluthra-globallogic , sorry to hear you're having problems with Selenium Wire and Safari.

Are you able to use Safari with Selenium itself? i.e. no proxy settings or Selenium Wire, just regular remote control.

**Comment by sluthra-globallogic** [comment]
Hi @wkeeling 

Yes , I am able to run safari with selenium with proxy off and even i am able to run safari with selenium wire provided  with adequate proxy settings as mentioned in the document provided it will only work when the charles proxy or mitmproxy is working , else it wont work .

Need Help !

Regards,
Sukrant

**Comment by wkeeling** [comment]
@sluthra-globallogic ok interesting. 

Could you post the code that creates the webdriver and the settings that are being passed to it?

Also, do you have environment variables `http_proxy` or `https_proxy` configured anywhere - e.g. in your test script or `.bashrc`?

**Comment by sluthra-globallogic** [comment]
@wkeeling 

Please find the code below : 

def open_safari_browser(url):
    options = {
        'port': 8080
    }
    driver = headerDriver.Safari(seleniumwire_options=options, executable_path='/usr/bin/safaridriver')
    headers = {
        "bbm-version": 1,
        "User-Agent": "Mozilla/5.0 (Linux; Android 6.0.1; SM-G920V Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36",
    }
    driver.header_overrides = headers
    driver.get(url)


No,  I have not set environment variables http_proxy and https_proxy anywhere, can you please help me how to do that. 


Regards,
Sukrant

**Comment by sluthra-globallogic** [comment]
@wkeeling   I did set the environment variable in bash_profile to give a try but still getting the same issue.

Regards,
Sukrant

**Comment by wkeeling** [comment]
Thanks @sluthra-globallogic 

Your webdriver config seems ok. The reason I asked about the environment variables is because if these are set, Selenium Wire will automatically try and use them. So if these variables are pointing at charles/mithm and charles/mithm are not running, then Selenium Wire will not work.

Could you try and explicitly set these variables to `None` in the options you pass to webdriver - like this:

```
options = {
    'port': 8080
    'proxy': {
        'http': None,
        'https': None
    }
}
driver = headerDriver.Safari(seleniumwire_options=options, executable_path='/usr/bin/safaridriver')
```

**Comment by sluthra-globallogic** [comment]
@wkeeling It worked when i set the proxy in the option plus i have also set the proxy enabled in network settings for http and https .

But doing this my normal internet surfing wont work , is there any way that both things work at the same time . 

Thanks

**Comment by wkeeling** [comment]
@sluthra-globallogic With Safari, the proxy settings have to be manually set for Selenium Wire to work, which means that they would need to be unset if you wanted to surf the net using that browser. This is a limitation of the web driver API supported by Safari.

With Firefox and Chrome however, these browsers can have their proxy settings automatically configured by Selenium Wire _per test session_ which means that the settings are removed when the session ends, and thus do not interfere with normal internet surfing.

Safari's manual configuration is due to lack of support in the web driver API, it's not a limitation of Selenium Wire itself.

**Comment by sluthra-globallogic** [comment]
@wkeeling  thanks for your help. Does there any way we can automate the safari manual configuration ?

**Comment by wkeeling** [comment]
@sluthra-globallogic sorry for the delay in replying. I'm afraid I'm not aware of a way to automate the proxy setup for Safari. I guess it might be possible to script it somehow, although without some investigation I wouldn't know how to do that.
