### ISSUE TITLE
How to turn seleniumwire headless?

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#244]
It's compleltly missing in the docs, i figured it out after a couple minutes, but it would be no harm to just add it into the docs

**Comment by wkeeling** [comment]
Thanks for pointing this out. The headless property isn't specific to Selenium Wire - it's a Selenium webdriver option that can be passed to the driver with `selenium.webdriver.chrome.options.Options` and `selenium.webdriver.firefox.options.Options` for Chrome and Firefox respectively.

Since running in headless mode seems to be a common use-case for Selenium Wire, I've now mentioned it in the README and linked to the relevant Selenium API docs.
