### ISSUE TITLE
Request.body documentation update

### ISSUE THREAD

**Issue by alexis-evelyn** [wkeeling/selenium-wire#245]
I wanted to mention, I had to use `request.response.body` in order to get the body, `request.body` returns an empty byte array.

Chrome version is `Version 89.0.4389.82 (Official Build) (x86_64)` on OSX. ChromeDriver version is an unmodified version of `ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294})`

My requirements.txt for you.
```ini
blinker==1.4
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.6
EasyProcess==0.3
feedparser==6.0.2
h11==0.12.0
h2==4.0.0
hpack==4.0.0
hyperframe==6.0.0
idna==2.10
kaitaistruct==0.9
lxml==4.6.2
pyasn1==0.4.8
pycparser==2.20
pyOpenSSL==20.0.1
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.1
PyVirtualDisplay==2.1
requests==2.25.1
selenium==3.141.0
selenium-wire==4.2.1
sgmllib3k==1.0.0
six==1.15.0
urllib3==1.26.3
wsproto==1.0.0
xmltodict==0.12.0
```

* https://pypi.org/project/selenium-wire/

**Comment by wkeeling** [comment]
Thank you for raising this issue.

If the outbound request was a GET request then `request.body` will be empty because GET requests have no body (they just send the URL and some headers). The inbound response will normally have a body which will contain the html page, image, script etc. The exception for this is redirect responses which will have an empty response body.

So with standard GET requests, it is normal for `request.body` to be empty and `request.response.body` to contain the response payload.

**Comment by alexis-evelyn** [comment]
Thanks! I did not know that and was confused if my version of Chrome broke it until I experimented and figured out how to get the body.
