### ISSUE TITLE
last request errors?

### ISSUE THREAD

**Issue by Chris230291** [wkeeling/selenium-wire#248]
Hello. I am quite new to python in general so sorry if there are any obvious mistakes here.
I am trying to continuously get the last request that is different from the previous one...

```
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-setuid-sandbox')
chrome_options.add_argument('--disable-extensions')

driver = webdriver.Chrome('chromedriver', options=chrome_options)

driver.get("https://news.sky.com/watch-live")

prev_request = None

while True:
    request = driver.last_request
    if request != prev_request:
        prev_request = request
        if request.response:
            print (request.response.headers['Content-Type'])
``` 

I am getting errors though...

```
C:\Users\Chris>python C:\Users\Chris\Downloads\test.py

DevTools listening on ws://127.0.0.1:51328/devtools/browser/604abfd0-cbb2-4655-bf99-786ab577bc1c
[15840:13528:0318/150649.877:ERROR:device_event_log_impl.cc(214)] [15:06:49.877] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.
video/mp4
video/mp4
video/mp4
video/mp4
audio/mp4
audio/mp4
audio/mp4
Traceback (most recent call last):
  File "C:\Users\Chris\Downloads\test.py", line 15, in <module>
    request = driver.last_request
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\seleniumwire\inspect.py", line 49, in last_request
    return self.proxy.storage.load_last_request()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\seleniumwire\storage.py", line 225, in load_last_request
    return self._load_request(last_request.id)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\seleniumwire\storage.py", line 166, in _load_request
    with open(os.path.join(request_dir, 'request'), 'rb') as req:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Chris\\.seleniumwire\\storage-42b9615e-cbca-4c55-bb7b-30aa98bf5525\\request-a7a6dc72-aa7e-45c2-bd5b-af48934dd952\\request'

C:\Users\Chris>
```

Can anyone explain why I get the errors?

Is this polling even the best way of achieving what I want?
I am trying to see if the last request was a video stream, if it was I want to pipe it into ffmpeg... I haven't figured out that part yet, though.

Thanks,
Chris

**Comment by wkeeling** [comment]
Many thanks for raising this. 

It looks like you've uncovered a bug - a timing issue that can happen in certain cases when a request has not been fully saved. In most cases it's unlikely to happen, but is more likely to occur when request retrieval happens repeatedly in quick succession - like in your situation when you call `driver.last_request` in a loop. It's now fixed in v4.2.2.

In your case though, since you want to take some action based on a particular type of response, I wonder if it would be better to use a response interceptor rather than polling. If you know the content type of the video stream, you should be able to do something such as:

```
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-setuid-sandbox')
chrome_options.add_argument('--disable-extensions')

driver = webdriver.Chrome('chromedriver', options=chrome_options)

def interceptor(request, response):
    if response.headers['Content-Type'] == 'video/mp4':  # Change content type if required
        # Do something with the response -
        # e.g. pipe response.body into ffmpeg

driver.response_interceptor = interceptor
driver.get("https://news.sky.com/watch-live")
```

**Comment by Chris230291** [comment]
Thanks. I updated and it no longer crashes.
I like your suggestion better though.
The only problem I have is that I need to add "while True: pass" to the bottom of your example to keep it alive. Is this normal?

**Comment by wkeeling** [comment]
Ah yes good point, once the script finishes, Selenium Wire will shutdown and the interceptor will no longer execute - so yes, you'd need to have something to keep the script alive whilst the response is being processed. You could also maybe look at using 
```
input('press enter to continue')
``` 
which would achieve the same thing, but you could just hit enter rather than having to kill the program with CTRL-C in the case of the "while True".
