### ISSUE TITLE
HTTP Response 501 when PATCH requests made under selenium-wire

### ISSUE THREAD

**Issue by psymps** [wkeeling/selenium-wire#32]
When making PATCH requests using selenium-wire, I get a HTTP Error 501 as a response. On further inspection, some response headers are missing. The following screenshot captures the state of the headers under selenium-wire:

![fail](https://user-images.githubusercontent.com/26301313/52279873-747e4480-2952-11e9-844c-6f660962377c.PNG)

The next screenshot captures the state of the headers when not using selenium-wire:

![pass](https://user-images.githubusercontent.com/26301313/52279735-2c5f2200-2952-11e9-8b7a-55d8ffe20ca5.PNG)

I would like to know why the "Allow" header is not present when using selenium-wire.

**Comment by wkeeling** [comment]
@psymps Thanks for raising this.

What's happening here is Selenium Wire is rejecting the PATCH request because that method hasn't been mapped in Selenium Wire's embedded proxy server. The request therefore never makes it to the target server, and the response that you see contains only the headers from the proxy server itself.

This has been fixed in version 1.0.1 and PATCH requests are now being correctly proxied.
