### ISSUE TITLE
The problem with the authentication agent

### ISSUE THREAD

**Issue by Mankvis** [wkeeling/selenium-wire#409]
Because I used an authentication proxy, when the page was loaded (successfully used the proxy) but it was refreshed again, there was a proxy error ERR_PROXY_CONNECTION_FAILED

The agent is no problem

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in replying.

This is likely happening because you are refreshing the browser after your code/script finishes. When the script finishes, Selenium Wire shuts down and so the browser can no longer talk to it for request/response interception.

One way to resolve is to use a `time.sleep()` at the end of your script to pause it before it ends. Whilst it is paused, you can refresh the browser.
