### ISSUE TITLE
Selenium wire doesn't add request header

### ISSUE THREAD

**Issue by felipesantos989** [wkeeling/selenium-wire#412]
Hi, i'm trying to add a header to all requests, using the command below that is on the documentation, but it doesn't add the request header at all.
the website loads, not complete, but loads, but when i try to reload i get this error below: ERR_PROXY_CONNECTION_FAILED

i think these two errors have something in common, probably the website isn't accepting proxy or not accepting being intercepted, is it? 
is there something that i can do to bypass it (if is this)?

```
from seleniumwire import webdriver

# chrome driver
PATH = "C:/Users/Unknown/Documents/Selenium/chromedriver.exe"
driver = webdriver.Chrome(PATH)


def interceptor(request):
    request.headers['New-Header'] = 'Some Value'

driver.request_interceptor = interceptor
# All requests will now contain New-Header

# navigate to website
driver.get('http://www.examplewebsite.com')
```

**Comment by wkeeling** [comment]
Thanks for raising this.

With regard to your first issue, how are you confirming whether the request header has been set? Note that the browser's network tab won't show you the header, because Selenium Wire sets the header _after_ it has left the browser. It is best to use something such as https://httpbin.org/headers for checking the presence of the header.

With regard to the second issue, if you try and reload the page in the browser after the script has ended, then Selenium Wire will have shut down so I would expect to see the message `ERR_PROXY_CONNECTION_FAILED`. If you want to manually reload, you'll need to keep the code running at the end. 

For example you could use a `time.sleep(60)` to achieve that:
```python
import time
from seleniumwire import webdriver

# chrome driver
PATH = "C:/Users/Unknown/Documents/Selenium/chromedriver.exe"
driver = webdriver.Chrome(PATH)


def interceptor(request):
    request.headers['New-Header'] = 'Some Value'

driver.request_interceptor = interceptor
# All requests will now contain New-Header

# navigate to website
driver.get('http://www.examplewebsite.com')
time.sleep(60)  # Pause here allowing you to manually refresh the page
```

**Comment by felipesantos989** [comment]
Yes, i was checking on the chrome network tab.
using sleep i was able to reload page.

Thank you so much for your help!
