### ISSUE TITLE
weird behavior (slow loading page) when using disable_encoding

### ISSUE THREAD

**Issue by trimbilrepo** [wkeeling/selenium-wire#423]
Hiii...

I am experiencing really slow page loading time when using _disable_encoding_ in one of my machine.
even it stop loading on instagram and facebook.
but working fine in other machine with the same setup with different OS (Centos 7, Ubuntu 18.04 and OSX)

my setup for slow machine:
```
Ubuntu 20.14
seleniumwire 4.4.1
selenium 3.141.0
geckodriver 0.29.1
Firefox 93.0
```

```
seleniumwire_options = { 'disable_encoding' : True}
driver = webdriver.Firefox(seleniumwire_options=seleniumwire_options)
```

it took 30 seconds more to fully open facebook and instagram and working fine on selenium and normal browsing.

removing seleniumwire options disable_encoding give much more faster loading time.

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in responding. 

When `disable_encoding` is set to `True` it tells the server (well it "asks" the server) to send the response body without compressing it. That would likely cause a small reduction in performance since more bytes are being transmitted over the wire, but 30 seconds seems excessive. It's also strange that it affects one machine in particular. I don't have any answers at the moment but if you have any insights yourself, feel free to update here.
