### ISSUE TITLE
importing uc from seleniumwire ignores proxy option

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#483]
On newer versions of undetected chromedriver, I need to use this arg ``use_subprocess=True`` else I can't run it without getting a Runtime error. (https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/432) This argument seems to break the usage of proxies with selenium wire though.

```python
import seleniumwire.undetected_chromedriver.v2 as uc
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.headless = False
seleniumwire_options = {'proxy': {'https': 'type://host:port',}} 
driver = uc.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options, use_subprocess=True)

driver.get('https://whatismyipaddress.com/')
```

Ignores passed proxy option and loads website without proxy.

**Comment by wkeeling** [comment]
I've tried reproducing this, but my configured proxy continues to be used when `use_subprocess=True` is supplied.

```python
chrome_options = webdriver.ChromeOptions()
chrome_options.headless = False

driver = uc.Chrome(options=chrome_options, seleniumwire_options={
    'proxy': {
        'https': 'https://localhost:8080'
    }
}, use_subprocess=True)

driver.get('https://www.wikipedia.org/')
driver.quit()
```
For the above test I've set up a local proxy listening on `localhost:8080`. I can see from looking at the proxy log files that the requests are passing through the proxy. 

To further prove that the proxy is definitely in use, I ran the above code using an incorrect proxy port number (`8081`). The code failed to run as Selenium Wire was unable to reach `8081` - indicating that it is definitely not trying to bypass the proxy.

@Avnsx I'm not sure that `use_subprocess=True` is the issue here. Perhaps something else is going on in your environment which is causing the proxy to be bypassed?

**Comment by adv-zl** [comment]
Try import seleniumwire.undetected_chromedriver as uc and proxy with auth. It's not working
But in v2 everythingn is ok

**Comment by saitishmukhametov** [comment]
same issue here, even if u put random number in the proxy settings, it still bypasses it. 
using selenium-wire undetected chromedrive v1 (since i cant load extensions in v2)

**Comment by Sourly** [comment]
Hi. My problem...
The https://bot.sannysoft.com/ page opens.
You can briefly see "WebDriver Advanced - passed". :D

But, it doesn't take 3sec and already the browser closes. 
The address bar also changes to "not safe".
![000056](https://user-images.githubusercontent.com/1446365/153120032-382ff4b9-6d95-4270-aebb-f85d5d7aed45.png)
Someone has an idea? 

`selenium-wire==4.6.0`
`undetected_chromedriver==3.1.3`
`chromedriver==99.0.4844.17`

**Comment by Avnsx** [comment]
can confirm that https://github.com/wkeeling/selenium-wire/pull/509 fixes the issue for me 👏✔
