### ISSUE TITLE
CloudFlare Detects seleniumwire uc v2, although it doesn't detect the original uc selenium driver

### ISSUE THREAD

**Issue by deini-synamedia** [wkeeling/selenium-wire#489]
Tried to run this code on v2 and got CloudFlare's Anti Bot Captcha.
When running v1, CloudFlare doesn't detect us but no driver.requests are saved.

  ```
 import seleniumwire.undetected_chromedriver.v2 as uc
from seleniumwire import webdriver

options = webdriver.ChromeOptions()
options.headless = False

driver = uc.Chrome(options=options)

driver.get('https://whatismyipaddress.com/')
```

**Comment by wkeeling** [comment]
Thanks for raising this. This has been reported [before](https://github.com/wkeeling/selenium-wire/issues/215) and it's likely caused by TLS fingerprinting. Selenium Wire changes the TLS fingerprint when it captures requests and services such as CloudFlare are able to detect that. Unfortunately there's no solution at the current time but it's being tracked in #215.
