### ISSUE TITLE
driver.get() on some site issue

### ISSUE THREAD

**Issue by mastrolube** [wkeeling/selenium-wire#491]
Hi there!
I have a problem with seleniun-wire that gets stuck with certain websites.
I've added an exception to "fix" that, but I'm not understanding what's the problem here.
```
from selenium.common.exceptions import TimeoutException
from seleniumwire import webdriver
# from selenium import webdriver
import os

load_timeout = 15  # timeout for loading website
driver_path = r"C:\drivers\chromedriver.exe"
if not os.path.isfile(driver_path):
    raise FileNotFoundError
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(
    options=options, executable_path=driver_path
)
driver.set_page_load_timeout(load_timeout)

site_list = ["https://www.google.com", "https://www.github.com", "https://www.qq.com", "https://www.samakal.com", "https://www.bing.com", "https://www.guardian.ng","https://www.yahoo.com", "https://www.lindaikejisblog.com", "https://www.yahoo.com"]

for idx, site in enumerate(site_list, start=1):
    print(f"Opening {idx}: {site}")
    try:
        driver.get(site)
    except TimeoutException:
        print("The site did not load completely.")
driver.quit()
print("Finish!")
```
This is the result:
![immagine](https://user-images.githubusercontent.com/52335835/151356251-dfc0f512-0559-49cc-af10-1bb6805d48b0.png)

If I repeat the test I could get a different result.
Any advice?
Thanks!

Ps. With pure selenium, it never freezes.

**Comment by wkeeling** [comment]
It looks as though requests for embedded content (e.g. advertising, analytics) occasionally hit the timeout limit triggering the `TimeoutException` and the `The site did not load completely` message.

Selenium Wire adds extra I/O overhead in order to intercept/decrypt requests and this can sometimes cause requests to take longer. One suggestion would be to exclude certain requests from interception (e.g. advertising, analytics, trackers) using the [`exclude_hosts` option](https://github.com/wkeeling/selenium-wire#all-options). This will reduce the load on Selenium Wire and should improve page load performance.
