### ISSUE TITLE
"Loading 'screen' into random state - done" is printed multiple without changing website.

### ISSUE THREAD

**Issue by t0malbrecht** [wkeeling/selenium-wire#52]
"Loading 'screen' into random state - done" is printed multiple without changing website.
Also the Website is displayed as "unsecure", which means the SSL-Certificate is not created properly.

Here is the Code:
 options={
            'proxy': {
            'http': 'http://***************************',
            'https': 'https://***************************',
            'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
            }
        }

driver = webdriver.Chrome(seleniumwire_options=options)
driver.get("https://whatismyipaddress.com/")

I get that this must have to be failure of Opensll, but as in the installation of selenium-wire it is stated that is is included in the package, how can I try to solve it?

**Comment by wkeeling** [comment]
@t0malbrecht thanks for raising this.

I also noticed that the `Loading screen into random state` message is displayed when running on Windows, although it needs some investigation to determine the cause. However, from my own testing the message doesn't seem to lead to any harmful effects. I'll dig a little deeper and see if I can determine the root cause.

Regarding the browser showing "insecure", you are correct in saying that this is an issue with the SSL certificate not being created properly. From my investigation so far, it is because Chrome considers the root certificate invalid due to it missing a Subject Alternative Name - see #2  and #31 . I need to look at regenerating the root certificate with this field.

**Comment by wkeeling** [comment]
The `Loading screen into random state` is coming from openssl each time it generates a self-signed certificate. It seems as though this may be due to an inaccessible `.rnd` file, although it doesn't seem to cause any harmful effects.

**Comment by d383746** [comment]
Is there any way how to suppress those messages? They are really annoying and breaking text info coming from the real program. I even found this unneeded/unexpected output in official AWS documentation :).  So it means that the same openssl issue affecting other apps and people just ignore them because they are harmless.

**Comment by wkeeling** [comment]
@d383746 what version of selenium wire are you using, and also what OS? These OpenSSL messages were suppressed in 1.0.5 so I'm interested to understand why you're seeing them. Thanks!

**Comment by d383746** [comment]
It is on Windows 7 under GIT version of MINGW

Here is the version of selenium-wire. Should be the latest one.

pip install selenium-wire
Requirement already satisfied: selenium-wire in c:\app\python\python3\lib\site-packages (1.0.4)
Requirement already satisfied: selenium>=3.4.0 in c:\app\python\python3\lib\site-packages (from selenium-wire) (3.141.0)
Requirement already satisfied: urllib3 in c:\app\python\python3\lib\site-packages (from selenium>=3.4.0->selenium-wire) (1.25.2)
WARNING: You are using pip version 19.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


uname -a
MINGW64_NT-6.1 W7F054878TZ50A 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys


Output of a very simple program, similar to the one which is already presented to this page.
MINGW64
$ ./temp.py
Loading 'screen' into random state - done
Loading 'screen' into random state - done

**Comment by d383746** [comment]
Just tried the same under windows cmd shell and got the same output:

python temp.py
[13320:8752:0731/184734.563:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DnsPrefetchingEnabled
[13320:8752:0731/184734.973:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: DnsPrefetchingEnabled

DevTools listening on ws://127.0.0.1:52720/devtools/browser/44f8da70-a033-49a2-8bca-664dd0f619bf
Loading 'screen' into random state - done
Loading 'screen' into random state - done

**Comment by wkeeling** [comment]
It looks like you're running version 1.0.4 which does not contain the fix for the error messages:
```
Requirement already satisfied: selenium-wire in c:\app\python\python3\lib\site-packages (1.0.4)
```
You can upgrade to the latest version (1.0.7) by using the `--upgrade` argument:

```
pip install selenium-wire --upgrade
```

**Comment by d383746** [comment]
You are right. All good with the new version which I got via the --upgrade argument. 
Thanks a lot for the quick response and your great application.
