### ISSUE TITLE
Chrome --host-rules argument mapping to http not working

### ISSUE THREAD

**Issue by OliverTrust** [wkeeling/selenium-wire#527]
```python
options = ChromeOptions()
options.add_argument('--host-rules=MAP github.com 127.0.0.1:5000')
sw_options = {
    'verify_ssl': False
}
driver = Chrome(options=options, seleniumwire_options=sw_options)
driver.get('http://github.com')
```
![123](https://user-images.githubusercontent.com/33681835/162588775-6d0aebd7-4297-40bb-8b32-6f9a4f4ba6f1.png)

With selenium or with undetectable browser without selenium-wire, i easy connect to my local server with host rules

**Comment by testworldhapply** [comment]
me too

**Comment by wkeeling** [comment]
There is a bug with the `verify_ssl` option. Basically setting the value of the option to `False` will _switch on_ SSL verification - which will cause the "Cannot validate certificate hostname..." error you're seeing when using `--host-rules`.

This will be fixed in the next version. The immediate workaround is to set `verify_ssl=True` or omit it completely.
