### ISSUE TITLE
Dynamically switching between two proxy providers

### ISSUE THREAD

**Issue by randolfvalerija** [wkeeling/selenium-wire#538]
Hello,

not really an issue but more a question:

I have a case where I am using two upstream proxy providers to access data from different websites. Usually, the cheap one is good enough but sometimes I need the more "expensive" one. To optimize the usage of my "expensive" proxy provider and not burn through the request limit, I would like to wire requests like static assets through the cheap one and other requests through the expensive one.

My idea was to use a  request intercepter and dynamically switch between proxies depending on the URL that was intercepted (using regex e.g.). 

Would this be possible, or does this make sense? Is there maybe another way? I guess I could not use a proxy at all for static asset urls but I was just wondering one could use two separate proxies within selenium wire

**Comment by wkeeling** [comment]
Thanks for the issue/question.

Proxies are set at the webdriver level rather than per-request, so unfortunately it's not currently possible to switch the proxy on a request by request basis. You could block requests for static assets entirely using `request.abort()` to prevent them from going via the expensive proxy, but that would mean that the page may not render properly - which may not be what you want!
