### ISSUE TITLE
Selenium-wire didn't use socks configuration

### ISSUE THREAD

**Issue by Nicolas-Brossard** [wkeeling/selenium-wire#54]
Thanks a lot for your amazing job.

I've got one issue with selenium-wire :

I have a firefox profile configuration with socks parameter, It works well with selenium webdriver, but when I use selenium-wire webdriver, he didn't use those parameter

Thanks

`
profile = FirefoxProfile()`
`profile.set_preference('permissions.default.image', 2)`
`profile.set_preference('dom.ipc.plugins.enabled.libflashplayer.so', 'false')`
`profile.set_preference('network.proxy.type', 1)`
`profile.set_preference('network.proxy.socks', 'localhost')`
`profile.set_preference('network.proxy.socks_port', 9050)`
`profile.set_preference('network.proxy.socks_remote_dns', True)`
`profile.update_preferences()`

**Comment by wkeeling** [comment]
Hi - thanks for raising this. This is likely due to the fact that Selenium Wire overrides proxy configuration with its own proxy settings in order to capture requests. In order to use an upstream proxy, you have to use Selenium Wire's own [`proxy`](https://github.com/wkeeling/selenium-wire#proxies) configuration option. However, Selenium Wire doesn't offer any support for SOCKS, which it probably should. I'll investigate what is involved in supporting SOCKS based proxies.

**Comment by Nicolas-Brossard** [comment]
Thanks for your answer, works perfectly.
