### ISSUE TITLE
Is it possible to intercept requests without having to point the browser back to the proxy with remote?

### ISSUE THREAD

**Issue by jmtekin** [wkeeling/selenium-wire#547]
Hello!

I was wondering if there is a way to intercept requests and more specifically modify request headers without the remote browsers needing to know the ip of the proxy.

It feels like it should be possible since the path of the intercepted request wouldn't need to travel back to the proxy unless the captured response is desired. 

I would assume the path of a request would look something like (very likely to be wrong):
python -> proxy -> remote browser -> server
while the path of the response would be:
python <- proxy <- remote browser <- server
If the response is not needed it shouldn't be necessary to point the browser to the proxy right?

In case it is not possible, how would one deal with situations where the ip of the machine running selenium wire isn't accessible to the remote browser (gitlab CICD for example)?

**Comment by wkeeling** [comment]
Thanks for raising this.

Actually the proxy sits _after_ the browser, not before it:
```
python -> webdriver -> remote browser -> proxy -> server
```
The proxy and the interceptor both have to live on the same machine because they share the same Python process. So unfortunately this means that the IP of the machine running the proxy has to be accessible to the remote browser. Sorry to not have a more satisfactory answer.
