### ISSUE TITLE
Connection not secure on hhtps website

### ISSUE THREAD

**Issue by pedrosalesmiranda** [wkeeling/selenium-wire#91]
Linux Mint 19.1 Cinnamon
Cinnamon version 4.0.10
Linux Kernel 4.15.0-55-generic
Browser Chrome
OpenSSL 1.1.1  11 Sep 2018

I get warning in top bar of chrome of not secure connection and with driver from selenium i get the locker icon. It gets the headers from requests but I think I got some issues with facebook about fishing I believe its related to this not secure warning.

Please tell me if i can give you extra information that can be valuable for you.

**Comment by wkeeling** [comment]
Thanks @pedrosalesmiranda.

The issue is that Selenium Wire's root certificate has not been installed in Chrome. To install the certificate, you first need to extract it from Selenium Wire by running:

     python -m seleniumwire extractcert

That will produce a file called `ca.crt` in the current working directory. You then need to go into Chrome's preferences, navigate to "Manage certificates", click the "Authorities" tab and then "IMPORT". Select the `ca.crt` file and ensure you check all the boxes regarding permissions. Then re-run your test.

**Comment by pedrosalesmiranda** [comment]
Now its perfect thank a lot for the help @wkeeling
